---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkwarden
  namespace: linkwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkwarden
  template:
    metadata:
      labels:
        app: linkwarden
    spec:
      containers:
        - name: linkwarden
          image: ghcr.io/linkwarden/linkwarden:latest
          env:
            - name: DATABASE_URL
              value: "postgresql://user:password@192.168.11.253:5434/database"
            - name: NEXTAUTH_SECRET
              value: "NfkbRhXdsCUW"
            - name: NEXTAUTH_URL
              value: "https://linkwarden.ecc-comp.com/api/v1/auth"
            - name: NEXT_PUBLIC_KEYCLOAK_ENABLED
              value: "true"
            - name: KEYCLOAK_ISSUER
              value: "http://keycloak.ecc-comp.com/realms/general"
            - name: KEYCLOAK_CLIENT_ID
              value: "linkwarden"
            - name: KEYCLOAK_CLIENT_SECRET
              value: "6EyVIJsWqqMfSsVLXfM0bUZlMgig84kX"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: linkwarden
  namespace: linkwarden
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: linkwarden
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: linkwarden
  namespace: linkwarden
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: linkwarden.ecc-comp.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: linkwarden
            port:
              number: 3000