---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: growi-ingress
  namespace: growi
spec:
  ingressClassName: nginx
  rules:
  - host: growi.yumekiti.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: growi-app-service
            port:
              number: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: growi-app-service
  namespace: growi
spec:
  selector:
    app: growi-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: growi-elasticsearch-service
  namespace: growi
spec:
  selector:
    app: growi-elasticsearch
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: growi-app
  namespace: growi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: growi-app
  template:
    metadata:
      labels:
        app: growi-app
    spec:
      containers:
      - image: weseek/growi:7.0.12
        name: growi-app
        ports:
        - containerPort: 3000
        env:
        - name: ELASTICSEARCH_URI
          value: http://growi-elasticsearch-service:9200/growi
        - name: AUDIT_LOG_ENABLED
          value: 'true'
        - name: MONGO_URI
          value: mongodb://10.201.10.61:27017/growi
        - name: PASSWORD_SEED
          value: NfkbRhXdsCUW
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: growi
data:
  elasticsearch.yml: |
    http.host: 0.0.0.0

    # for elasticsearch-head
    http.cors.enabled: true
    http.cors.allow-origin: "*"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: growi-elasticsearch
  namespace: growi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: growi-elasticsearch
  template:
    metadata:
      labels:
        app: growi-elasticsearch
    spec:
      containers:
      - name: growi-elasticsearch
        image: extendwings/growi-elasticsearch:7.17.19
        ports:
        - containerPort: 9200
        env:
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        - name: LOG4J_FORMAT_MSG_NO_LOOKUPS
          value: "true"
        - name: bootstrap.memory_lock
          value: "true"
        volumeMounts:
        - name: config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
        resources:
          limits:
            memory: "1Gi"
#            memory: "512Mi"
          requests:
            memory: "512Mi"
#            memory: "256Mi"
      volumes:
      - name: config
        configMap:
          name: elasticsearch-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: growi-nginx-config
  namespace: growi
data:
  nginx.conf: |
    upstream growi {
        server growi-app-service:3000;
    }

    map $http_upgrade $connection_upgrade {
        default Upgrade;
        ''      close;
    }

    map $http_origin $cors{
      "https://blog.yumekiti.net" $http_origin;
      "http://blog.yumekiti.net" $http_origin;
    }

    server {
        listen 80;

        location / {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Port $server_port;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Original-URI $request_uri;
            proxy_pass http://growi;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_read_timeout 900s;

            # CORS
            add_header Access-Control-Allow-Origin $cors;
            add_header Access-Control-Allow-Methods '*';
            add_header Access-Control-Allow-Headers 'Content-Type';
            # add_header Access-Control-Allow-Credentials 'true';
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: growi-nginx
  namespace: growi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: growi-nginx
  template:
    metadata:
      labels:
        app: growi-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.27
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config-volume
        configMap:
          name: growi-nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: growi-nginx-service
  namespace: growi
spec:
  selector:
    app: growi-nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort